module.exports = [
  "1",
	"Welcome",
	"Glad you joined!",
	"Thank you for joining the discord server.",
	"You were always part of this server",
	"Nice to meet you",
	"I knew you will join my server",
	"Glad, we finally meet.",
	"What a plesant day.",
	"Welcome to World's best Discord server",
	"Wait a minute! who are you",
	"Are you serious bro",
	"Your Computer is working man",
]